[WLED]
# The IP address of the WLED device
#WLED_IP_ADDRESS = 192.168.1.45
# Using Multicast IP to feed all WLEDs on the same network
WLED_IP_ADDRESS = 239.0.0.1

#WLED_IPS = ["192.168.98.175", "192.168.98.155"]

# The UDP port for the connection (default: 11988)
WLED_UDP_PORT = 12988

[Audio]
# The sample rate of the audio stream (default for Shairport is 88200)
#sample_rate = 88200
sample_rate = 48000

# Size of the buffer in bytes (increase to add more delay)
buffer_size = 163840

# Size of the data chunks in bytes (increase to reduce bandwidth usage)
chunk_size = 8192
